name: imagesquared
favicon: null
layout_spectrum: 0.4073773417621851
typography_spectrum: 0.8878697631880641
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.03708940534852445
  lightness: 0.7895319347735494
  saturation: 0.9141104058362544
  rhythmicContrast: 0.7206681815441698
purpose: []
